/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.7.7-363
 *
 */
import { FluencePeer } from '@fluencelabs/fluence';
import type { CallParams$$ } from '@fluencelabs/fluence/dist/internal/compilerSupport/v4'
import {
    callFunction$$,
    registerService$$,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v4';


// Services

export interface IOnboardingServiceDef {
    get_location_game: (onboardInput: { arcade: string; arcadeSize: string; banner: string; description: string; developer: string; facebook: string; gameName: string; gameURL: string; genre: string[]; instagram: string; linkedin: string; screenshot: string[]; twitter: string; wallet: string; youtube: string; }, callParams: CallParams$$<'onboardInput'>) => { arcade_image: string; game_url: string; location_id: string; status: { message: string; status_code: number; success: boolean; }; width: number; x: number; y: number; } | Promise<{ arcade_image: string; game_url: string; location_id: string; status: { message: string; status_code: number; success: boolean; }; width: number; x: number; y: number; }>;
    insert_arcade_building: (arcade_detail: { arcade_image: string; game_url: string; location_id: string; status: { message: string; status_code: number; success: boolean; }; width: number; x: number; y: number; }, callParams: CallParams$$<'arcade_detail'>) => { buildingId: string; locationId: string; status: { message: string; status_code: number; success: boolean; }; wallet: string; } | Promise<{ buildingId: string; locationId: string; status: { message: string; status_code: number; success: boolean; }; wallet: string; }>;
    update_mongodb_location: (locationDetail: { buildingId: string; locationId: string; status: { message: string; status_code: number; success: boolean; }; wallet: string; }, callParams: CallParams$$<'locationDetail'>) => { message: string; status_code: number; success: boolean; } | Promise<{ message: string; status_code: number; success: boolean; }>;
}
export function registerIOnboardingService(serviceId: string, service: IOnboardingServiceDef): void;
export function registerIOnboardingService(peer: FluencePeer, serviceId: string, service: IOnboardingServiceDef): void;
       

export function registerIOnboardingService(...args: any) {
    registerService$$(
        args,
        {
    "functions" : {
        "tag" : "labeledProduct",
        "fields" : {
            "get_location_game" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "onboardInput" : {
                            "tag" : "struct",
                            "name" : "OnboardInput",
                            "fields" : {
                                "arcadeSize" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "genre" : {
                                    "tag" : "array",
                                    "type" : {
                                        "tag" : "scalar",
                                        "name" : "string"
                                    }
                                },
                                "description" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "linkedin" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "developer" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "facebook" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "screenshot" : {
                                    "tag" : "array",
                                    "type" : {
                                        "tag" : "scalar",
                                        "name" : "string"
                                    }
                                },
                                "twitter" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "arcade" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "instagram" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "wallet" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "youtube" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "gameName" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "gameURL" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "banner" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                }
                            }
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "struct",
                            "name" : "ArcadeDetail",
                            "fields" : {
                                "y" : {
                                    "tag" : "scalar",
                                    "name" : "f32"
                                },
                                "location_id" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "status" : {
                                    "tag" : "struct",
                                    "name" : "StatusMessage",
                                    "fields" : {
                                        "message" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "status_code" : {
                                            "tag" : "scalar",
                                            "name" : "f32"
                                        },
                                        "success" : {
                                            "tag" : "scalar",
                                            "name" : "bool"
                                        }
                                    }
                                },
                                "game_url" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "width" : {
                                    "tag" : "scalar",
                                    "name" : "f32"
                                },
                                "x" : {
                                    "tag" : "scalar",
                                    "name" : "f32"
                                },
                                "arcade_image" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                }
                            }
                        }
                    ]
                }
            },
            "insert_arcade_building" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "arcade_detail" : {
                            "tag" : "struct",
                            "name" : "ArcadeDetail",
                            "fields" : {
                                "y" : {
                                    "tag" : "scalar",
                                    "name" : "f32"
                                },
                                "location_id" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "status" : {
                                    "tag" : "struct",
                                    "name" : "StatusMessage",
                                    "fields" : {
                                        "message" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "status_code" : {
                                            "tag" : "scalar",
                                            "name" : "f32"
                                        },
                                        "success" : {
                                            "tag" : "scalar",
                                            "name" : "bool"
                                        }
                                    }
                                },
                                "game_url" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "width" : {
                                    "tag" : "scalar",
                                    "name" : "f32"
                                },
                                "x" : {
                                    "tag" : "scalar",
                                    "name" : "f32"
                                },
                                "arcade_image" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                }
                            }
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "struct",
                            "name" : "LocationDetail",
                            "fields" : {
                                "buildingId" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "locationId" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "status" : {
                                    "tag" : "struct",
                                    "name" : "StatusMessage",
                                    "fields" : {
                                        "message" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "status_code" : {
                                            "tag" : "scalar",
                                            "name" : "f32"
                                        },
                                        "success" : {
                                            "tag" : "scalar",
                                            "name" : "bool"
                                        }
                                    }
                                },
                                "wallet" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                }
                            }
                        }
                    ]
                }
            },
            "update_mongodb_location" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "locationDetail" : {
                            "tag" : "struct",
                            "name" : "LocationDetail",
                            "fields" : {
                                "buildingId" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "locationId" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "status" : {
                                    "tag" : "struct",
                                    "name" : "StatusMessage",
                                    "fields" : {
                                        "message" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "status_code" : {
                                            "tag" : "scalar",
                                            "name" : "f32"
                                        },
                                        "success" : {
                                            "tag" : "scalar",
                                            "name" : "bool"
                                        }
                                    }
                                },
                                "wallet" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                }
                            }
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "struct",
                            "name" : "StatusMessage",
                            "fields" : {
                                "message" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "status_code" : {
                                    "tag" : "scalar",
                                    "name" : "f32"
                                },
                                "success" : {
                                    "tag" : "scalar",
                                    "name" : "bool"
                                }
                            }
                        }
                    ]
                }
            }
        }
    }
}
    );
}
      
// Functions
export type Onboard_gameArgOnboardInput = { arcade: string; arcadeSize: string; banner: string; description: string; developer: string; facebook: string; gameName: string; gameURL: string; genre: string[]; instagram: string; linkedin: string; screenshot: string[]; twitter: string; wallet: string; youtube: string; } 
export type Onboard_gameResult = { arcade_image: string; game_url: string; location_id: string; status: { message: string; status_code: number; success: boolean; }; width: number; x: number; y: number; }
export function onboard_game(
    onboardInput: Onboard_gameArgOnboardInput,
    config?: {ttl?: number}
): Promise<Onboard_gameResult>;

export function onboard_game(
    peer: FluencePeer,
    onboardInput: Onboard_gameArgOnboardInput,
    config?: {ttl?: number}
): Promise<Onboard_gameResult>;

export function onboard_game(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                          (call %init_peer_id% ("getDataSrv" "onboardInput") [] onboardInput)
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (call "12D3KooWEFFCZnar1cUJQ3rMWjvPQg6yMV2aXWs2DkJNSRbduBWn" ("op" "noop") [])
                       )
                       (call %init_peer_id% ("onboardingservice" "get_location_game") [onboardInput] get_location_game)
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [get_location_game])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                    )
    `
    return callFunction$$(
        args,
        {
    "functionName" : "onboard_game",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                "onboardInput" : {
                    "tag" : "struct",
                    "name" : "OnboardInput",
                    "fields" : {
                        "arcadeSize" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "genre" : {
                            "tag" : "array",
                            "type" : {
                                "tag" : "scalar",
                                "name" : "string"
                            }
                        },
                        "description" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "linkedin" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "developer" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "facebook" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "screenshot" : {
                            "tag" : "array",
                            "type" : {
                                "tag" : "scalar",
                                "name" : "string"
                            }
                        },
                        "twitter" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "arcade" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "instagram" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "wallet" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "youtube" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "gameName" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "gameURL" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "banner" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                }
            }
        },
        "codomain" : {
            "tag" : "unlabeledProduct",
            "items" : [
                {
                    "tag" : "struct",
                    "name" : "ArcadeDetail",
                    "fields" : {
                        "y" : {
                            "tag" : "scalar",
                            "name" : "f32"
                        },
                        "location_id" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "status" : {
                            "tag" : "struct",
                            "name" : "StatusMessage",
                            "fields" : {
                                "message" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "status_code" : {
                                    "tag" : "scalar",
                                    "name" : "f32"
                                },
                                "success" : {
                                    "tag" : "scalar",
                                    "name" : "bool"
                                }
                            }
                        },
                        "game_url" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "width" : {
                            "tag" : "scalar",
                            "name" : "f32"
                        },
                        "x" : {
                            "tag" : "scalar",
                            "name" : "f32"
                        },
                        "arcade_image" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                }
            ]
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}
